-- CREATE TRANSACTIONBYDATE 
CREATE TABLE TRANSACTIONBYDATE AS 
(SELECT DATE, SUM(QTY)
FROM TRANSACTION 
GROUP BY DATE
ORDER BY DATE);

-- CREATE CUSTOMERBYDATE 
CREATE TABLE CUSTOMERBYDATE AS 
(SELECT DATE, COUNT(DISTINCT CUSTOMERID)
FROM TRANSACTION 
GROUP BY DATE
ORDER BY DATE);

-- CREATE DATASET FOR CUSTOMER SEGMENTATION
CREATE TABLE CUSTOMERSEGMENTATION AS (SELECT C.CUSTOMERID, C.AGE, C.INCOME, 
SUM(T.TOTALAMOUNT) TOTAL_AMOUNT, COUNT(DISTINCT TRANSACTIONID) TOTAL_TRANSACTION,
(EXTRACT(YEAR FROM AGE(CURRENT_DATE, MAX(DATE)))*365 + EXTRACT(MON FROM AGE(CURRENT_DATE, MAX(DATE))) * 30 + EXTRACT(DAY FROM AGE(CURRENT_DATE, MAX(DATE)))) AS RECENCY
FROM CUSTOMER C JOIN TRANSACTION T ON C.CUSTOMERID = T.CUSTOMERID GROUP BY C.CUSTOMERID)