-- -- CREATE TRANSACTIONBYDATE 
-- CREATE TABLE TRANSACTIONBYDATE AS 
-- (SELECT DATE, SUM(QTY)
-- FROM TRANSACTION 
-- GROUP BY DATE
-- ORDER BY DATE);

-- -- CREATE CUSTOMERBYDATE 
-- CREATE TABLE CUSTOMERBYDATE AS 
-- (SELECT DATE, COUNT(DISTINCT CUSTOMERID)
-- FROM TRANSACTION 
-- GROUP BY DATE
-- ORDER BY DATE);

-- -- CREATE DATASET FOR CUSTOMER SEGMENTATION
-- CREATE TABLE CUSTOMERSEGMENTATION AS 
-- (SELECT C.*, COUNT(T.TRANSACTIONID) TOTALTRANSACTION, SUM(T.QTY) TOTALQTY, SUM(T.TOTALAMOUNT) TOTALAMOUNT
-- FROM CUSTOMER C
-- RIGHT JOIN TRANSACTION T ON T.CUSTOMERID = C.CUSTOMERID
-- GROUP BY C.CUSTOMERID);